import { Poppins } from 'next/font/google';
import './globals.css';
import { CartProvider } from '@/context/CartContext';
import { FiltersProvider } from '@/context/FiltersContext';
import Footer from '@/components/shared/Footer/Footer';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  fallback: ['Proxima Nova', 'system-ui', 'sans-serif'],
});

export const metadata = {
  title: 'E-comm',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/Icon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <CartProvider>
          <FiltersProvider>{children}</FiltersProvider>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
